# This file is part of OM.
#
# OM is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# OM is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with OnDA.
# If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2020 -2023 SLAC National Accelerator Laboratory
#
# Based on OnDA - Copyright 2014-2019 Deutsches Elektronen-Synchrotron DESY,
# a research centre of the Helmholtz Association.
[project]
authors = [{name = "OM Developement Team", email = "valmar@slac.stanford.edu"}]
name = "ondamonitor"
requires-python = ">= 3.11"
version = "0.1.0"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
description="Real-time monitoring of x-ray imaging experiments"
readme="README.md"
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Natural Language :: English",
  "Intended Audience :: Science/Research",
]
dependencies = [ "h5py", "numpy", "pillow", "pyzmq", "scipy", "cython>=3.1.2,<4", "fabio>=2024.9.0,<2025", "hdf5plugin>=5.1.0,<6", "msgpack>=1.1.1,<2", "msgpack-numpy>=0.4.8,<0.5", "pydantic>=2.10.0,<3", "pyyaml>=6.0.2,<7", "rich>=14.0.0,<15", "ruamel-yaml>=0.18.14,<0.19", "typer>=0.16.0,<0.17"]

[project.urls]
Homepage = "https://www.ondamonitor.com"
Repository = "httpd://github.com/omdevteam/om"

[project.scripts]
om_monitor = "om.monitor:run"
om_jungfrau_dark = "om.tools.jungfrau_dark:run"
om_jungfrau_zmq_receiver = "om.tools.jungfrau_zmq_receiver:run"

[project.gui-scripts]
om_crystallography_gui = "om.graphical_interfaces.crystallography_gui:run"
om_frame_viewer = "om.graphical_interfaces.frame_viewer:run"
om_crystallography_parameter_tweaker = "om.graphical_interfaces.crystallography_parameter_tweaker:run"
om_xes_gui = "om.graphical_interfaces.xes_gui:run"
om_swaxs_gui = "om.graphical_interfaces.swaxs_gui:run"

[build-system]
requires = ["setuptools", "numpy", "cython"]
build-backend = "setuptools.build_meta"

[tool.pyright]
diagnosticMode = "workspace"
typeCheckingMode = "strict"
venvPath = "/sdf/group/lcls/ds/tools/om/conda"
venv = "ps_20250819_miniom"

[tool.isort]
py_version = 311
profile = "black"

[tool.mypy]
show_error_codes = true
python_version = 3.11

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
