# This file is part of OM.
#
# OM is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation, either
# version 3 of the License, or (at your option) any later version.
#
# OM is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with OnDA.
# If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2020 -2023 SLAC National Accelerator Laboratory
#
# Based on OnDA - Copyright 2014-2019 Deutsches Elektronen-Synchrotron DESY,
# a research centre of the Helmholtz Association.
[project]
authors = [{name = "OM Developement Team", email = "valmar@slac.stanford.edu"}]
name = "ondamonitor"
requires-python = ">= 3.11"
version = "0.1.0"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
description="Real-time monitoring of x-ray imaging experiments"
readme="README.md"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Natural Language :: English",
    "Intended Audience :: Science/Research",
]
dependencies = [
    "cython",
    "fabio",
    "hdf5plugin",
    "h5py",
    "msgpack-python",
    "msgpack-numpy",
    "pillow",
    "pydantic",
    "pyyaml",
    "pyzmq",
    "rich",
    "ruamel-yaml",
    "scipy",
    "typer",
    "jinja2",
    "typing-extensions",
    "ansi2html",
    "PyQt5",
    "pyqtgraph",
    "ruamel-yaml-jinja2",
    "sortedcontainers",
    "mpi4py",
    "sphinx",
    "myst-parser",
    "pydata-sphinx-theme",
    "sphinx-click",
    "sphinxcontrib-images",
    "mypy",
    "h5py-stubs",
    "scipy-stubs",
    "types-pyyaml",
    "msgpack-types",
    "types-requests"
]

[project.urls]
Homepage = "https://www.ondamonitor.com"
Repository = "httpd://github.com/omdevteam/om"

[project.scripts]
om_monitor = "om.monitor:app"
om_jungfrau_dark = "om.tools.jungfrau_dark:run"
om_jungfrau_zmq_receiver = "om.tools.jungfrau_zmq_receiver:run"

[project.gui-scripts]
om_crystallography_gui = "om.graphical_interfaces.crystallography_gui:app"
om_frame_viewer = "om.graphical_interfaces.frame_viewer:app"
om_crystallography_parameter_tweaker = "om.graphical_interfaces.crystallography_parameter_tweaker:app"
om_xes_gui = "om.graphical_interfaces.xes_gui:app"
om_swaxs_gui = "om.graphical_interfaces.swaxs_gui:app"

[build-system]
requires = ["setuptools", "numpy", "cython"]
build-backend = "setuptools.build_meta"

[tool.basedpyright]
reportMissingTypeStubs = false
typeCheckingMode = "strict"

[tool.isort]
py_version = 311
profile = "black"

[tool.mypy]
show_error_codes = true
python_version = 3.11

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = [
   { name = "linux-64-pypi", platform = "linux-64", glibc="2.28" },
   { name = "linux-64-cds", platform = "linux-64", glibc = "2.17" },
]

[tool.pixi.feature.xtcpp]
channels = ["lcls-ii"]
platforms = ["linux-64-pypi"]

[tool.pixi.feature.psana2]
channels = ["lcls-ii"]
platforms = ["linux-64-pypi"]

[tool.pixi.feature.psana1]
channels = ["lcls-i"]
platforms = ["linux-64-pypi"]

[tool.pixi.feature.psana2cds]
channels = ["lcls-ii"]
platforms = ["linux-64-cds"]

[tool.pixi.feature.psana1cds]
channels = ["lcls-i"]
platforms = ["linux-64-cds"]

[tool.pixi.pypi-dependencies]
ondamonitor = { path = ".", editable = true }

[tool.pixi.feature.psana2cds.pypi-options]
no-build-isolation = ["ondamonitor"]

[tool.pixi.feature.psana1cds.pypi-options]
no-build-isolation = ["ondamonitor"]

[tool.pixi.environments]
psana1 = ["psana1"]
psana2 = ["psana2"]
psana1cds = ["psana1cds"]
psana2cds = ["psana2cds"]
xtcpp = ["xtcpp"]

[tool.pixi.feature.xtcpp.activation]
scripts = ["activation-xtcpp.sh"]

[tool.pixi.feature.psana2.activation]
scripts = ["activation-psana2.sh"]

[tool.pixi.feature.psana1.activation]
scripts = ["activation-psana1.sh"]

[tool.pixi.feature.psana2cds.activation]
scripts = ["activation-psana2-cds.sh"]

[tool.pixi.feature.psana1cds.activation]
scripts = ["activation-psana1-cds.sh"]

[tool.pixi.feature.xtcpp.dependencies]
python = "3.13.*"
openmpi = { version = "5*", channel = "conda-forge" }
mpi4py = { version = "*", channel = "conda-forge" }
hdf5 = { version = "*", channel = "conda-forge" }
h5py = { version = "*", channel = "conda-forge" }
pip = { version = "*", channel = "conda-forge" }
gxx_linux-64 = { version = "*", channel = "conda-forge" }
zlib = { version = "*", channel = "conda-forge" }
patchelf = { version = "*", channel = "conda-forge" }

[tool.pixi.feature.psana2.dependencies]
python = "3.13.*"
psana = { version="==4.3.1", channel="lcls-ii" }
openmpi = { version = "4*", channel = "conda-forge" }
mpi4py = { version = "*", channel = "conda-forge" }
prometheus-cpp = { version = "*", channel = "conda-forge" }

[tool.pixi.feature.psana1.dependencies]
python = "3.11.*"
psana = { version="==4.0.66", channel="lcls-i" }
openmpi = { version = "4*", channel = "conda-forge" }
mpi4py = { version = "*", channel = "conda-forge" }

[tool.pixi.feature.psana2cds.dependencies]
python = "3.13.*"
psana = { version = "==4.3.1", channel = "lcls-ii" }
openmpi = { version = "4*", channel = "conda-forge" }
mpi4py = { version = "*", channel = "conda-forge" }
h5py = { version = "*", channel = "conda-forge" }
numpy = { version = "*", channel = "conda-forge" }
scipy = { version = "*", channel = "conda-forge" }
pyqtgraph = { version = "*", channel = "conda-forge" }
hdf5 = { version = "*", channel = "conda-forge" }
matplotlib = { version = "*", channel = "conda-forge" }
fabio = { version = "*", channel = "conda-forge" }
hdf5plugin = { version = "*", channel = "conda-forge" }
msgpack-python = { version = "*", channel = "conda-forge" }
msgpack-numpy = { version = "*", channel = "conda-forge" }
prometheus-cpp = { version = "*", channel = "conda-forge" }

[tool.pixi.feature.psana1cds.dependencies]
python = "3.11.*"
psana = { version = "==4.0.66", channel = "lcls-i" }
openmpi = { version = "4*", channel = "conda-forge" }
mpi4py = { version = "*", channel = "conda-forge" }
h5py = { version = "*", channel = "conda-forge" }
numpy = { version = "*", channel = "conda-forge" }
scipy = { version = "*", channel = "conda-forge" }
pyqtgraph = { version = "*", channel = "conda-forge" }
hdf5 = { version = "*", channel = "conda-forge" }
matplotlib = { version = "*", channel = "conda-forge" }
fabio = { version = "*", channel = "conda-forge" }
hdf5plugin = { version = "*", channel = "conda-forge" }
msgpack-python = { version = "*", channel = "conda-forge" }
msgpack-numpy = { version = "*", channel = "conda-forge" }

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ty.analysis]
allowed-unresolved-imports = ["psana"]
