#!/usr/bin/env bash

source /reg/g/psdm/bin/conda_setup

export LD_LIBRARY_PATH=${ONDA_INSTALLATION_DIR}/python_extensions/:${LD_LIBRARY_PATH}
export PYTHONPATH=${ONDA_INSTALLATION_DIR}:${ONDA_HIDRA_API_DIR}:${PYTHONPATH}
export PATH=${ONDA_INSTALLATION_DIR}:${ONDA_INSTALLATION_DIR}/GUI/:${ONDA_INSTALLATION_DIR}/tools/:${PATH}
