export LD_LIBRARY_PATH=${ONDA_INSTALLATION_DIR}/python_extensions/:/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}
export PYTHONPATH=${ONDA_INSTALLATION_DIR}:${PYTHONPATH}
export PATH=${ONDA_INSTALLATION_DIR}:${ONDA_INSTALLATION_DIR}/GUI/:${ONDA_INSTALLATION_DIR}/tools/:${PATH}

