# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OndaCrystallographyParameterTweakerUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 818)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout0 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout0.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout0.setObjectName("verticalLayout0")
        self.imageView = ImageView(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageView.sizePolicy().hasHeightForWidth())
        self.imageView.setSizePolicy(sizePolicy)
        self.imageView.setBaseSize(QtCore.QSize(0, 0))
        self.imageView.setObjectName("imageView")
        self.verticalLayout0.addWidget(self.imageView)
        self.horizontalLayout0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout0.setObjectName("horizontalLayout0")
        self.backButton = QtWidgets.QPushButton(self.layoutWidget)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout0.addWidget(self.backButton)
        self.forwardButton = QtWidgets.QPushButton(self.layoutWidget)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout0.addWidget(self.forwardButton)
        self.randomButton = QtWidgets.QPushButton(self.layoutWidget)
        self.randomButton.setObjectName("randomButton")
        self.horizontalLayout0.addWidget(self.randomButton)
        self.showHidePeaksCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.showHidePeaksCheckBox.setChecked(True)
        self.showHidePeaksCheckBox.setObjectName("showHidePeaksCheckBox")
        self.horizontalLayout0.addWidget(self.showHidePeaksCheckBox)
        self.verticalLayout0.addLayout(self.horizontalLayout0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        spacerItem = QtWidgets.QSpacerItem(20, 732, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout1.addItem(spacerItem)
        self.hitLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.hitLabel.setObjectName("hitLabel")
        self.verticalLayout1.addWidget(self.hitLabel)
        self.resolutionRingsCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.resolutionRingsCheckBox.setChecked(True)
        self.resolutionRingsCheckBox.setObjectName("resolutionRingsCheckBox")
        self.verticalLayout1.addWidget(self.resolutionRingsCheckBox)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.lastClickedPositionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastClickedPositionLabel.sizePolicy().hasHeightForWidth())
        self.lastClickedPositionLabel.setSizePolicy(sizePolicy)
        self.lastClickedPositionLabel.setObjectName("lastClickedPositionLabel")
        self.horizontalLayout1.addWidget(self.lastClickedPositionLabel)
        self.lastClickedPixelValueLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lastClickedPixelValueLabel.sizePolicy().hasHeightForWidth())
        self.lastClickedPixelValueLabel.setSizePolicy(sizePolicy)
        self.lastClickedPixelValueLabel.setObjectName("lastClickedPixelValueLabel")
        self.horizontalLayout1.addWidget(self.lastClickedPixelValueLabel)
        self.verticalLayout1.addLayout(self.horizontalLayout1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.forwardButton.setText(_translate("MainWindow", "Forward"))
        self.randomButton.setText(_translate("MainWindow", "Random"))
        self.showHidePeaksCheckBox.setText(_translate("MainWindow", "Show/Hide Peaks"))
        self.hitLabel.setText(_translate("MainWindow", "Hit: - (- peaks)"))
        self.resolutionRingsCheckBox.setText(_translate("MainWindow", "Min and max resolution rings"))
        self.lastClickedPositionLabel.setText(_translate("MainWindow", "Last clicked position: - "))
        self.lastClickedPixelValueLabel.setText(_translate("MainWindow", "Pixel value: - "))

from pyqtgraph import ImageView
