site_name: OnDA Monitor - v23.8.2
site_dir: ../docs/html
extra_css:
  - assets/css/extra.css
theme:
  name: material
  features:
    - navigation.top
  icon:
    logo: material/alpha-o-box-outline
    repo: fontawesome/brands/github
markdown_extensions:
  - admonition
  - def_list
  - mkdocs-click
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
copyright: Copyright &copy; 2020-2023 OM Development Team
repo_url: https://github.com/omdevteam/om
edit_uri: ''
repo_name: omdevteam/om
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: false
            members_order: source
            heading_level: 1
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["psana"] = mock()
            - sys.modules["mpi4py"] = mock()
  - search

nav:
  - What is OM?: index.md
  - Installing OM: installing_om.md
  - Running OM: running_om.md
  - Configuring OM: configuring_om.md
  - Advanced Documentation: advanced_documentation.md
  - The OM Development Team: the_om_development_team.md
  - Code Reference:
    - om:
      - __init__: reference/om/index.md
      - algorithms:
        - __init__: reference/om/algorithms/index.md
        - calibration: reference/om/algorithms/calibration.md
        - crystallography: reference/om/algorithms/crystallography.md
        - generic: reference/om/algorithms/generic.md
        - xes: reference/om/algorithms/xes.md
      - data_retrieval_layer:
        - __init__: reference/om/data_retrieval_layer/index.md
        - data_event_handlers_asapo: reference/om/data_retrieval_layer/data_event_handlers_asapo.md
        - data_event_handlers_files: reference/om/data_retrieval_layer/data_event_handlers_files.md
        - data_event_handlers_http: reference/om/data_retrieval_layer/data_event_handlers_http.md
        - data_event_handlers_psana: reference/om/data_retrieval_layer/data_event_handlers_psana.md
        - data_event_handlers_zmq: reference/om/data_retrieval_layer/data_event_handlers_zmq.md
        - data_retrieval_asapo: reference/om/data_retrieval_layer/data_retrieval_asapo.md
        - data_retrieval_files: reference/om/data_retrieval_layer/data_retrieval_files.md
        - data_retrieval_http: reference/om/data_retrieval_layer/data_retrieval_http.md
        - data_retrieval_psana: reference/om/data_retrieval_layer/data_retrieval_psana.md
        - data_retrieval_zmq: reference/om/data_retrieval_layer/data_retrieval_zmq.md
        - data_sources_asapo: reference/om/data_retrieval_layer/data_sources_asapo.md
        - data_sources_files: reference/om/data_retrieval_layer/data_sources_files.md
        - data_sources_psana: reference/om/data_retrieval_layer/data_sources_psana.md
        - data_sources_generic: reference/om/data_retrieval_layer/data_sources_generic.md
        - data_sources_http: reference/om/data_retrieval_layer/data_sources_http.md
        - data_sources_zmq: reference/om/data_retrieval_layer/data_sources_zmq.md
        - event_retrieval: reference/om/data_retrieval_layer/event_retrieval.md
      - graphical_interfaces:
        - __init__: reference/om/graphical_interfaces/index.md
        - common: reference/om/graphical_interfaces/common.md
        - crystallography_gui: reference/om/graphical_interfaces/crystallography_gui.md
        - crystallography_parameter_tweaker: reference/om/graphical_interfaces/crystallography_parameter_tweaker.md
        - frame_viewer: reference/om/graphical_interfaces/frame_viewer.md
        - xes_gui: reference/om/graphical_interfaces/xes_gui.md
      - lib:
        - __init__: reference/om/lib/index.md
        - cheetah: reference/om/lib/cheetah.md        
        - crystallography: reference/om/lib/crystallography.md
        - event_management: reference/om/lib/event_management.md
        - exceptions: reference/om/lib/exceptions.md
        - geometry: reference/om/lib/geometry.md
        - hdf5: reference/om/lib/hdf5.md
        - layer_management: reference/om/lib/layer_management.md
        - parameters: reference/om/lib/parameters.md
        - rich_console: reference/om/lib/rich_console.md
        - xes: reference/om/lib/xes.md        
        - zmq_qt: reference/om/lib/zmq_qt.md
        - zmq: reference/om/lib/zmq.md
      - parallelization_layer:
        - __init__: reference/om/parallelization_layer/index.md
        - mpi: reference/om/parallelization_layer/mpi.md
        - multiprocessing: reference/om/parallelization_layer/multiprocessing.md
      - processing_layer:
        - __init__: reference/om/processing_layer/index.md
        - cheetah_streaming: reference/om/processing_layer/cheetah_streaming.md
        - cheetah: reference/om/processing_layer/cheetah.md
        - crystallography: reference/om/processing_layer/crystallography.md
        - testing: reference/om/processing_layer/testing.md
        - xes: reference/om/processing_layer/xes.md
      - protocols:
        - __init__: reference/om/protocols/index.md
        - data_retrieval_layer: reference/om/protocols/data_retrieval_layer.md
        - parallelization_layer: reference/om/protocols/parallelization_layer.md
        - processing_layer: reference/om/protocols/processing_layer.md
      - monitor: reference/om/monitor.md
